### ISSUE TITLE
Documentation or Project Example

### ISSUE THREAD

**Issue by ztroop** [boydjohnson/firebase-auth-lite-rs#1]
I found this project through Reddit. I'm glad to see I'm not the only one thinking Firebase would be useful in a `yew`/`wasm` context. The work you've done is fantastic! Thanks for putting this together.

As a suggestion or request, I think it would be nice to have an `example` project that illustrates usage.

**Comment by boydjohnson** [comment]
Hi @ztroop I will work on both more documentation for the README.md and an example project that uses Firebase.

**Comment by ztroop** [comment]
Cool! Much appreciated!

**Comment by boydjohnson** [comment]
Let me know if the example app now in the repo is enough for you. It does email and password signup and login with yew as the framework.

**Comment by ztroop** [comment]
Perfect! It's very easy to follow. Thank you!
